Page({
  data:{
    src:'/images/c.png',
    btnc:'active',
    btnd:'inactive',
    btne:'inactive',
    btnf:'inactive',
    btng:'inactive',
    btna:'inactive',
    btnb:'inactive',
  },
  c:function(){
    this.setData({
      src:'/images/c.png',
      btnc:'active',
      btnd:'inactive',
      btne:'inactive',
      btnf:'inactive',
      btng:'inactive',
      btna:'inactive',
      btnb:'inactive'
    })
  },
  d:function(){
    this.setData({
      src:'/images/d.png',
      btnc:'inactive',
      btnd:'active',
      btne:'inactive',
      btnf:'inactive',
      btng:'inactive',
      btna:'inactive',
      btnb:'inactive'
    })
  },
  e:function(){
    this.setData({
      src:'/images/e.png',
      btnc:'inactive',
      btnd:'inactive',
      btne:'active',
      btnf:'inactive',
      btng:'inactive',
      btna:'inactive',
      btnb:'inactive'
    })
  },
  f:function(){
    this.setData({
      src:'/images/f.png',
      btnc:'inactive',
      btnd:'inactive',
      btne:'inactive',
      btnf:'active',
      btng:'inactive',
      btna:'inactive',
      btnb:'inactive'
    })
  },
  g:function(){
    this.setData({
      src:'/images/g.png',
      btnc:'inactive',
      btnd:'inactive',
      btne:'inactive',
      btnf:'inactive',
      btng:'active',
      btna:'inactive',
      btnb:'inactive'
    })
  },
  a:function(){
    this.setData({
      src:'/images/d.png',
      btnc:'inactive',
      btnd:'inactive',
      btne:'inactive',
      btnf:'inactive',
      btng:'inactive',
      btna:'active',
      btnb:'inactive'
    })
  },
  b:function(){
    this.setData({
      src:'/images/b.png',
      btnc:'inactive',
      btnd:'inactive',
      btne:'inactive',
      btnf:'inactive',
      btng:'inactive',
      btna:'inactive',
      btnb:'active'
    })
  }
})
