//index.js
//获取应用实例
Page({
  data:{
    list:[
      [
        {text:'朋友圈',icon:'/images/moments.png'}
      ],
      [
        {text:'扫一扫',icon:'/images/scan.png'},
        {text:'摇一摇',icon:'/images/shake.png'}
      ],
      [
        {text:'看一看',icon:'/images/topStories.png'},
        {text:'搜一搜',icon:'/images/search.png'}
      ],
      [
        {text:'购物',icon:'/images/shopping.png'},
        {text:'游戏',icon:'/images/games.png'}
      ],
      [
        {text:'小程序',icon:'/images/miniProgram.png'}
      ]
    ],
  }
})
